version: '3.8'
services:
  web:
    image: nginx:1.14.2  # Vulnerable version
    ports:
      - "80:80"
    environment:
      - DATABASE_PASSWORD=admin123  # Hardcoded secret
    privileged: true  # Security risk
    user: root  # Running as root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket exposure
    
  database:
    image: mysql:5.6.51  # Vulnerable MySQL version
    environment:
      - MYSQL_ROOT_PASSWORD=password123  # Weak password
      - MYSQL_DATABASE=app
    ports:
      - "3306:3306"  # Exposed database port
    
  redis:
    image: redis:5.0.0  # Vulnerable Redis version
    ports:
      - "6379:6379"  # Exposed Redis port
    command: redis-server --protected-mode no  # Disabled security