apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-nginx
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2  # Vulnerable version
        ports:
        - containerPort: 80
        securityContext:
          runAsUser: 0       # Running as root
          privileged: true   # Privileged container
        env:
        - name: SECRET_KEY
          value: "hardcoded-secret-123"  # Hardcoded secret
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  password: cGFzc3dvcmQxMjM=  # base64 encoded "password123"